# Generated by Django 4.2 on 2023-04-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=30)),
                ('DepartmentEmail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=60)),
                ('EmployeeCharge', models.CharField(max_length=20)),
                ('EmployeeNumber', models.IntegerField(max_length=10)),
                ('EmployeeEmail', models.EmailField(max_length=100)),
                ('EmployeeCI', models.IntegerField(max_length=10)),
                ('EmployeeRIF', models.CharField(max_length=15)),
                ('EmployeeAddress', models.CharField(max_length=250)),
                ('EmployeeBirthday', models.CharField(max_length=10)),
                ('EmployeeShirtSize', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=15)),
                ('EmployeeShoesSize', models.IntegerField(max_length=2)),
                ('EmployeePantSize', models.IntegerField(max_length=2)),
                ('EmployeeAdmission', models.CharField(max_length=10)),
                ('EmployeeEmergencyContact', models.CharField(max_length=60)),
                ('EmployeeEmergencyNumber', models.IntegerField(max_length=10)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.department')),
            ],
        ),
    ]
