# Generated by Django 4.2 on 2023-04-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CellCity', models.CharField(choices=[('CCS', 'Caracas'), ('GUA', 'Guatire-Guarenas'), ('CAU', 'Caucagua'), ('HIG', 'Higuerote')], max_length=15)),
                ('CellName', models.CharField(max_length=60)),
                ('CellAddress', models.CharField(max_length=100)),
                ('CellCoord', models.CharField(max_length=60)),
                ('CellHeight', models.IntegerField(max_length=100)),
                ('CellContact', models.CharField(max_length=60)),
                ('CellContactNumber', models.IntegerField(max_length=10)),
            ],
        ),
    ]
