# Generated by Django 4.2 on 2023-04-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='CellContactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cells',
            name='CellHeight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeCI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeEmergencyNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeePantSize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeShoesSize',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Act', models.CharField(choices=[('SOPORTE', 'Soporte'), ('INSTALACION', 'Instalacion'), ('CELDAFULL', 'Full dia de celda'), ('CELDAMEDIA', 'Medio dia de celda')], max_length=20)),
                ('DateAsig', models.CharField(max_length=10)),
                ('DateRes', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('COMPLETADO', 'Completado'), ('NO FINALIZADO', 'No finalizado')], max_length=20)),
                ('Ciudad', models.CharField(choices=[('SOPORTE', 'Soporte'), ('INSTALACION', 'Instalacion'), ('CELDAFULL', 'Full dia de celda'), ('CELDAMEDIA', 'Medio dia de celda')], max_length=20)),
                ('Celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.cells')),
            ],
        ),
    ]
