# Generated by Django 4.2 on 2023-04-26 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_cells_cellcontactnumber_alter_cells_cellheight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Person1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_1', to='reports.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='Person2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_2', to='reports.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='Person3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_3', to='reports.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='Person4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_4', to='reports.employee'),
            preserve_default=False,
        ),
    ]
