# Generated by Django 4.2 on 2023-04-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_activity_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_2', to='reports.employee'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Person3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_3', to='reports.employee'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Person4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contratis_4', to='reports.employee'),
        ),
    ]
