# Generated by Django 4.2 on 2023-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_activity_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Cliente',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
